### ISSUE TITLE
OMS Agent should build on Linux ARM (32 bit or 64 bit) but fails

### ISSUE THREAD

**Issue by jkatzmandu** [microsoft/Build-OMS-Agent-for-Linux#160]
I've tried building this source on Rasbpian on a Pi B 3+ (32 bit) and on Ubuntu 64 bit (Pi 4.) I've gotten interesting failures both times:

I wanted an OMS Agent and syslog daemon running at home for a test Sentinel instance. All I have these days are Raspberry Pis. Note that these instructions assume some Linux/Unix familiarity. I may make the instructons a bit more "universal" and easily read at a later date.

1) I stated with Raspbian on a Pi B 3+. If you're using Ubuntu you may be able to skip some of these steps because Raspbian is a hair different as it aims to be more lightweight.
2) Change /bin/sh to link to /bin/bash instead of /bin/dash. (cd /bin; rm sh; ln -s bash sh) The ./configure shell scripts expect specific POSIX behaviour which dash doesn't have.
3) Install GNU-awk (apt install gawk) and change /usr/bin/awk to link to /usr/bin/gawk. Again, ./configure scripts expect GNU-awk behaviour.
4) Follow the instructions here to use 'git clone' to get the latest codebsae to your Pi: https://github.com/microsoft/Build-OMS-Agent-for-Linux
5) In addition to the packages listed in that repository you may need to install: libpam-dev, libgss-dev, and ruby.
6) From the instructions from the "master" branch URL above create the bld-omsagent/omsagent/test/config/systest.conf file.
7) Cross fingers and run "make." I was dumb and didn't time this, but you're looking at well over an hour.
8) -- I'm still dealing with a compile issue. Ruby itself seems to compile (why can't we just use the one installed on the system?) When Ruby goes to "========================= Performing Moving Ruby to intermediate directory" it craps out, complaining it can't find "ruby/config.h" ... some RTFM shows that "-I/home/pi/oms/bld-omsagent/omsagent/intermediate/Linux_ULINUX_1.0_UNKNOWN_64_Release/ruby/include/ruby-2.6.0/armv7l-linux-eabihf" is missing from the command line. When I add that, the compile fails badly as the default options complain that casting warnings should be treated as errors.

... so I tried again, this time on a Pi 4 running 64 Bit Ubuntu Server.
On the initial configure run it falied; I had to add 7 lines to bld-omsagent/omsagent/Unix/buildtool so that "aarch64" was a supported architecture, but still didn't get far.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
