### ISSUE TITLE
How to build the omsconfig package?

### ISSUE THREAD

**Issue by lizzha** [Microsoft/Build-OMS-Agent-for-Linux#21]
In the released omsagent-1.2.0-148.universal.x64.sh, it installs omi, scx, omsagent, and omsconfig packages. 
I followed the steps in Readme to build omsagent package on Ubuntu 14.04, and it comes out deb packages of omi, scx, and omsagent.  Then how to build the omsconfig package?

And when I install the built packages one by one, installing omsagent package outputs a log:
-su: /opt/microsoft/omsconfig/Scripts/OMS_MetaConfigHelper.py: No such file or directory
Is it normal behavior?

**Comment by carrguil** [comment]
How did you solve that issue?

I'm running into that same situation. I know omsconfig rpms are available in dsc-kits, bit it dosen't cover my architecture so I would like to build omsconfig just like I did for omsagent.
